# Generated by Django 3.2.8 on 2021-10-12 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roomorder', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('room', 'date', 'time_id')},
        ),
    ]
