# Generated by Django 3.2.8 on 2021-10-24 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomorder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='bookertel',
            new_name='tel',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='adminer',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='coursename',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='printel',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='teacher',
        ),
        migrations.AddField(
            model_name='book',
            name='adminer',
            field=models.CharField(default='尚未通过审批', max_length=32, verbose_name='实验室审批人'),
        ),
        migrations.AddField(
            model_name='book',
            name='coursename',
            field=models.CharField(default='', max_length=32, verbose_name='课程名称'),
        ),
        migrations.AddField(
            model_name='book',
            name='printel',
            field=models.CharField(default='', max_length=32, verbose_name='负责人及联系电话'),
        ),
        migrations.AddField(
            model_name='book',
            name='teacher',
            field=models.CharField(default='', max_length=32, verbose_name='负责老师'),
        ),
    ]
