# Generated by Django 3.2.9 on 2021-11-05 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomorder', '0002_auto_20211024_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='batch',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.DateField(verbose_name='借用日期'),
        ),
        migrations.AlterField(
            model_name='book',
            name='time_id',
            field=models.IntegerField(choices=[(1, '8:00~9:35'), (2, '9:50~12:05'), (3, '12:05~13:30'), (4, '13:30~15:05'), (5, '15:20~17:55'), (6, '18:00~19:20')], verbose_name='时间段'),
        ),
    ]
